### ISSUE TITLE
I18N – add English and Swedish to the UI

### ISSUE THREAD

**Issue by olpeh** [olpeh/onkometrorikki#5]
**Is your feature request related to a problem? Please describe.**
Finland is a multilingual  country, and Finnish is not the easiest language to understand.

**Describe the solution you'd like**
An easy way to select the preferred language in the UI. Store the selected language in local storage or cookie for use on later visits. Optionally add different languages as routes in order for direct linking by URL.

**Describe alternatives you've considered**
Alternatively, just keep the UI in Finnish but display the reasons for interruptions in all 3 languages that the HSL API already provides.

**Comment by farskid** [comment]
@olpeh I'd like to pick this for english. any hint for where to start?

**Comment by olpeh** [comment]
Hi @farskid 
My idea for approaching this has been the following:

- Modify the backend to return all languages instead of [just picking the finnish version](https://github.com/olpeh/onkometrorikki/blob/e6bcfc3b85be74c1086d54631ba473508547d120/backend/hsl.js#L108)
- Add a language selector to the UI, and displaying the UI and the traffic alerts in the selected language, possibly [following this blog post](https://paulfioravanti.com/blog/2018/05/11/runtime-language-switching-in-elm/) or any other elmy way of doing I18N. My idea was to not do it in the easiest way, but rather do it the "correct" way
- Save the language selection locally for next visits (also keep in mind that saving the selected theme would be nice)
- Add language to routing, for example onkometrorikki.fi/en etc.

 We could of course split this into smaller chunks and implement one step at a time or something

One challenge in implementing this is that the feed is the live data, I don't know if there is a test feed available that would always contain some service alerts. Testing this with live data would require the metro have some interruptions while developing.

**Comment by farskid** [comment]
@olpeh Sounds good to me. I'm on it.

**Comment by olpeh** [comment]
And also, there is no way at the moment to run it using a local backend easily. Should probably make that possible. Added as an issue #10

**Comment by olpeh** [comment]
@ohanhi has a nice approach for this in trains.today: https://github.com/ohanhi/trains/pull/9

Probably we could use a similar approach here.

**Comment by olpeh** [comment]
I will start working on this.
